// interface/src/components/header.tsx
import React from "react"

const Header = () => {
  return (
    <div className="flex items-center justify-between row-span-1 px-4 col-span-full">
      <p className="text-sm font-light">Authorship Attribution System</p>
      <svg
        className="w-8 h-8 p-1 font-bold transition duration-300 ease-in-out rounded-full hover:bg-purple-500 hover:text-gray-100"
        fill="none"
        stroke="currentColor"
        viewBox="0 0 24 24"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={2}
          d="M12 6v6m0 0v6m0-6h6m-6 0H6"
        />
      </svg>
    </div>
  )
}

export default Header

// vue-app/src/components/header.vue
<template>
	<div className="flex items-center justify-between row-span-1 px-4 col-span-full">
		<p className="text-sm font-light">Authorship Attribution System</p>
		<svg
			className="w-8 h-8 p-1 font-bold transition duration-300 ease-in-out rounded-full hover:bg-purple-500 hover:text-gray-100"
			fill="none"
			stroke="currentColor"
			viewBox="0 0 24 24"
			xmlns="http://www.w3.org/2000/svg"
		>
			<path strokeLinecap="round" strokeLinejoin="round" strokeWidth="{2}" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
		</svg>
	</div>
</template>

<script>
export default {};
</script>
